Embed 메세지 발송
webdonalds/discord-bot pull request #41
Opened 2021-07-03 09:15 UTC by inc5025

resolves #40 

수정 내역
- command의 execute의 리턴 타입을 새로운 응답 타입(ResponseMessage)으로 수정하였습니다.
- embed message 생성을 위한 util을 추가하였습니다.
- `!help` 커멘드에 대해서 Embed 메세지를 적용하였습니다.

2021-07-03 10:20 UTC, hellodhlyn reviewed
`utils.Embed` 의 역할은 `responses.EmbedMessage` 에서 처리해도 괜찮을 것 같습니다

2021-07-03 10:20 UTC, hellodhlyn commented on bot.go
> +	"github.com/webdonalds/discord-bot/responses"
internal 패키지는 가장 아래에 작성

2021-07-03 10:20 UTC, hellodhlyn commented on bot.go
> +			_, _ = s.ChannelMessageSend(m.ChannelID, "명령어 파싱에 실패했습니다.")
굳이 여기서 보내지 않고 `res = NewTextMessage("...")` 로 메시지 객체를 만들어서 발송 부분을 통일하면 좋겠습니다.

2021-07-03 10:20 UTC, hellodhlyn commented on commands/delivery.go
> +		return responses.NewTextMessage(""), nil, err
`nil` 을 리턴해도 무방할듯

2021-07-03 11:28 UTC, inc5025 commented on bot.go
> +			_, _ = s.ChannelMessageSend(m.ChannelID, "명령어 파싱에 실패했습니다.")
https://github.com/webdonalds/discord-bot/blob/4ff83c70dbfd7e487a1277a2e1b02f9d94c58245/commands/exchange.go#L74-L78

발송 부분을 통일하는 건 좋은데, 환율 처럼 res와 err 둘 다 값이 들어오는 경우가 있어 추후에 exchange.go를 수정할 필요가 있어보입니다.

2021-07-04 16:58 UTC, zych1751 requested changes
Embed 도입은 좋아보이네요 ㅎ_ㅎ

2021-07-04 16:58 UTC, zych1751 commented on responses/embed.go
> +}
endline이 없어요.

2021-07-04 16:58 UTC, zych1751 commented on responses/text.go
> +}
여기두

2021-07-04 16:58 UTC, zych1751 commented on commands/air_quality.go
> +	"github.com/webdonalds/discord-bot/responses"
아래로 내려가야 할 것 같네요.

2021-07-04 16:58 UTC, zych1751 commented on commands/exchange.go
> +	"github.com/webdonalds/discord-bot/responses"
여기도

2021-07-04 16:58 UTC, zych1751 commented on responses/embed.go
> +}
한번 더  EmbedMessage에서 한 depth 더 들어가서 Embed를 만든 이유가 따로 있을까요? 그냥 EmbedMessage에서 SetTitle, SetDescription ... 을 해도 상관 없어보여서요.

2021-07-04 16:58 UTC, zych1751 commented on responses/embed.go
> +	}
전체적으로 이런 패턴이 많이 보이는데, 새로 함수를 구현해도 좋을 것 같습니다.
(아래는 예시)
```suggestion
	if len(args) == 0 {
		return e
	}
	URL := getArgsOrDefault(args, 0, "")
```

2021-07-11 14:45 UTC, inc5025 commented on responses/embed.go
> +}
단지 `*discordgo.MessageEmbed`가 길어서 그랬습니다. 없어도 상관 없긴 합니다.

2021-07-11 14:48 UTC, inc5025 commented on responses/embed.go
> +	}
해당 부분은 그리 여러 번 반복되는 부분이 아니고, 더 많은 부분에서 사용될 코드도 아니라고 생각합니다. 그래서 새로 함수를 구현한다고 더 깔끔해지거나 짧아지진 않을 것 같고, 오히려 관련 함수들의 기능을 한번에 이해하기 위해 다른 곳을 또 읽어줘야하는 불편함이 생긴다고 생각합니다.

2021-07-11 14:52 UTC, inc5025 commented on commands/air_quality.go
> +	"github.com/webdonalds/discord-bot/responses"
한 번에 다 확인했어야 했는데, 생각 못 한 부분이 좀 있었네요. 수정하겠습니다.

2021-07-11 15:02 UTC, zych1751 commented on responses/embed.go
> +	}
setImage, setThumbnail, setAuthor 에서 같은 패턴이 반복되고 있어서 반복되는건 꽤 많다고 생각하긴 했고 변수선언, if문으로 나뉘어져있는 코드를 바로 선언하면서 값을 설정할 수 있으면 코드는 깔끔해질것 같아요.
그리고 함수를 구현했을때 naming만 잘한다면 굳이 함수내용을 안 읽어봐도 알 수 있을거고 읽는다고 하더라도 함수가 2줄정도 분량이라 큰 부담이 될것 같진 않아요

2022-03-11 04:52 UTC, closed without merging